
name: action-w-inputs-ex1
description: Replace-With-Your-Action-Description
inputs:
  path_dockerfile: ./src/main/docker/Dockerfile.jvm
  image_name: academy
  tag_name: $(date +%s)
  
runs:
  using: composite
  steps:
    #- run: docker build . --file ./src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)
    -run: docker build . --file ${{ inputs.path_dockerfile }} --tag ${{ inputs.image_name }}:${{ inputs.tag_name }}
      shell: bash
