name: Docker Push Image
description: "Action to Push the Project Docker Image to Docker Hub"
inputs:
  DOCKERHUB_USERNAME:
    description: "Docker UserName"
    required: true
  DOCKERHUB_TOKEN:
    description: "Docker Password"
    required: true

runs:
    using: 'composite'
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.DOCKERHUB_USERNAME }}
          password: ${{ inputs.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker push ${{ inputs.DOCKERHUB_USERNAME }}/academy:v1
        shell: bash
